### ISSUE TITLE
Suggestion: Sprayable enemies

### ISSUE THREAD

**Issue by DrivingCrooner** [AIOMEGA/LethalPlus#1]
I love the idea of spraying the bees to stun them. It would be really nice if this stunned or blinded some enemies too like a thumper or loot bug. I always panic and spray enemies with paint already and this would make me actually useful lol.

**Comment by AIOMEGA** [comment]
Wouldn't be a bad Idea but I think I would probably balance it by making it so they can still attack if they can hear you since while SprayPaint may get in your eyes and even block your smell your ears are unaffected.

**Comment by AIOMEGA** [comment]
I have added a basic version of your request but I plan on improving and expanding on it later on.
